language: scala
scala:
   - 2.12.2
jdk:
  - oraclejdk8
before_install:
  - wget -O amm https://github.com/lihaoyi/Ammonite/releases/download/1.0.0-RC6/2.12-1.0.0-RC6
  - chmod +x amm
script:
  - ./amm Runner.sc publish dev
